version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: php7.4
    container_name: client_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - localhost
  nginx:
    image: nginx:1.17-alpine
    container_name: client_nginx
    restart: unless-stopped
    ports:
      - 6000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - localhost
networks:
  localhost:
    driver: bridge